name: API Test Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 9 * * *'  # Run daily at 6 AM Brazil time (UTC-3)

# Add permissions section to ensure the action can access resources
permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Create Report Directories
      run: |
        mkdir -p target/surefire-reports
        mkdir -p target/site
        touch target/surefire-reports/.gitkeep
        touch target/site/.gitkeep
        
    - name: Run API Tests
      env:
        REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
      run: |
        mvn clean test -Dtest=* -Dmaven.test.failure.ignore=true -Dsurefire.useFile=false -Dsurefire.reportFormat=plain -X -e || true
        mkdir -p target/site
        
    - name: Debug Directory Structure
      if: always()
      run: |
        echo "Current directory:"
        pwd
        echo "Listing root directory:"
        ls -la
        echo "Listing target directory:"
        ls -la target/
        echo "Listing surefire-reports directory:"
        ls -la target/surefire-reports/
        echo "Listing site directory:"
        ls -la target/site/
        
    - name: Generate Test Report
      if: always()
      run: |
        mkdir -p target/site
        mvn surefire-report:report-only -e || true
        
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/site/
        retention-days: 7 